name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: yarn install
    - run: yarn build
    # - run: yarn test

    - uses: ./
      with:
        workingPath: ./example
        dockerUserName: silvenga-docker
        dockerPassword: ${{ secrets.GITHUB_TOKEN }}
        dockerImageName: silvenga-docker/build-image/example
        dockerTags: latest,${{ github.sha }}
